# Case Study 1

Test wether the number of nonrandom eigenvalues are a good proxy for the number of independent trials.

For each experiment the number of nonrandom eigenvalues should be equal to or greater than the number of independent trials.

The runtime should decrease when the max_scan paramter is added.

In [20]:
# Imports

import time 
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from marchenko_pastur import Signal

## Experiment 1: Randomly generated block correlation data

100 trials with 10 and 20 independent trials

250 trials with 10 and 25 independent trials

500 trials with 10 and 50 independent trials
 
1000 trials with 10 and 20 independent trials

### 100 trials with 10 and 20 independent trials

In [22]:
data_100_10 = pd.read_csv('Data/simulated_data_100_10p.csv')

In [23]:
model_100_10 = Signal(data_100_10)

eMax, var, nFacts0 = model_100_10.findMaxEval(data_100_10)

print(nFacts0)

10

In [24]:
data_100_20 = pd.read_csv('Data/simulated_data_100_20p.csv')

In [25]:
model_100_20 = Signal(data_100_20)

eMax, var, nFacts0 = model_100_20.findMaxEval(data_100_20)

print(nFacts0)

20

### 250 trials with 10 and 25 independent trials

In [26]:
data_250_10 = pd.read_csv('Data/simulated_data_250_10p.csv')

In [27]:
model_250_10 = Signal(data_250_10)

eMax, var, nFacts0 = model_250_10.findMaxEval(data_250_10)

print(nFacts0)

10

In [28]:
data_250_25 = pd.read_csv('Data/simulated_data_250_25.csv')

In [29]:
model_250_25 = Signal(data_250_25)

eMax, var, nFacts0 = model_250_25.findMaxEval(data_250_25)

print(nFacts0)

25

### 500 trials with 10 and 50 independent trials

In [30]:
data_500_10 = pd.read_csv('Data/simulated_data_500_10p.csv')

In [31]:
model_500_10 = Signal(data_500_10)

eMax, var, nFacts0 = model_500_10.findMaxEval(data_500_10)

print(nFacts0)

10

In [32]:
data_500_50 = pd.read_csv('Data/simulated_data_500_50p.csv')

In [33]:
model_500_50 = Signal(data_500_50)

eMax, var, nFacts0 = model_500_50.findMaxEval(data_500_50)

print(nFacts0)

50

### 1000 trials with 10 and 20 independent trials

In [34]:
data_1000_10 = pd.read_csv('Data/simulated_data_1000_10.csv')

In [35]:
model_1000_10 = Signal(data_1000_10)

eMax, var, nFacts0 = model_1000_10.findMaxEval(data_1000_10)

print(nFacts0)

10

In [36]:
data_1000_20 = pd.read_csv('Data/simulated_data_1000_20.csv')

In [37]:
model_1000_20 = Signal(data_1000_20)

eMax, var, nFacts0 = model_1000_20.findMaxEval(data_1000_20)

print(nFacts0)

20

## Experiment 2: S&P500 data

There should be a difference in runtime when using the max_scan parameter as part of the ONC algorithm.

In [21]:
data = pd.read_csv('Data/real_strategy_data.csv', index_col=0, parse_dates=True)
data = data.fillna(0)
data

,0,1,2,3,4,5,6,7,8,9,...,1030,1031,1032,1033,1034,1035,1036,1037,1038,1039
2013-03-18,-0.009287,-0.009287,-0.009287,-0.009287,-0.009287,-0.009287,-0.009287,-0.009287,-0.009287,-0.009287,...,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.000000
2013-03-19,0.000000,-0.002909,-0.002909,-0.002909,0.000000,-0.002909,-0.002909,-0.002909,0.000000,-0.002909,...,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.000000
2013-03-20,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.000000
2013-03-21,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.000000
2013-03-22,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-02-16,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,-0.014068,-0.014068,0.0,0.0,-0.014068,-0.014068
2023-02-17,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,-0.002988,-0.002988,0.0,0.0,-0.002988,-0.002988
2023-02-21,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.000000,-0.020000,0.0,0.0,0.000000,-0.020000
2023-02-22,-0.001685,-0.001685,-0.001685,-0.001685,-0.001685,-0.001685,-0.001685,-0.001685,-0.001685,-0.001685,...,0.0,0.0,0.0,0.0,0.000000,-0.001685,0.0,0.0,0.000000,-0.001685
2023-02-23,0.000000,0.003876,0.003876,0.003876,0.000000,0.003876,0.003876,0.003876,0.000000,0.003876,...,0.0,0.0,0.0,0.0,0.000000,0.003876,0.0,0.0,0.000000,0.003876

### Determine the minimum number of clusters to consider:

In [3]:
model_real_data = Signal(data)

eMax, var, nFacts0 = model_real_data.findMaxEval(data)

print(nFacts0)

41

### Run ONC with max_scan parameter:

In [4]:
from onc_fast import ONC

We add the input max_scan to incorporate the new information from specral decomposition

In [5]:
import os
os.environ["OMP_NUM_THREADS"] = '16'
# Supress all warnings due to running Kmeans on windows using all cores
import warnings
warnings.filterwarnings("ignore")
import time

# Fit ONC
start_time = time.time()
# set repeats as large as you can afford
model = ONC(data.corr(), repeat=450, max_scan=41)
print('Fitting')
model.fit()
end_time = time.time()
print("Time taken: ", end_time - start_time)

# Load from saved
# model2 = ONC(data.corr(), repeat=1)
# model2.load_results(pre_fix='official3')

Fitting
Max_scan: 6
5
improving now
Max_scan: 6
3
Time taken:  24451.688906431198

### The silhouette scores

In [6]:
model.get_silh_scores()

0       0.251217
1       0.282623
2       0.281864
3       0.281864
4       0.251217
          ...
1035    0.345230
1036    0.215230
1037    0.257312
1038    0.288098
1039    0.341168
Length: 1040, dtype: float64

### Check the sorted block correlation matrix

In [7]:
model.get_block_correlation()

,560,561,562,563,564,568,572,576,580,584,...,406,407,409,410,411,413,417,421,422,423
560,1.000000,0.642347,0.627133,0.627133,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,0.117602,0.115987,0.127690,0.116094,0.112681,0.117421,0.147476,0.134558,0.125899,0.125803
561,0.642347,1.000000,0.976286,0.976286,0.642347,0.642347,0.642347,0.642347,0.642347,0.642347,...,0.294141,0.290108,0.282731,0.285459,0.277075,0.259991,0.274889,0.284120,0.282589,0.282374
562,0.627133,0.976286,1.000000,1.000000,0.627133,0.627133,0.627133,0.627133,0.627133,0.627133,...,0.303473,0.299299,0.279607,0.293736,0.285091,0.257162,0.271633,0.285065,0.297832,0.297603
563,0.627133,0.976286,1.000000,1.000000,0.627133,0.627133,0.627133,0.627133,0.627133,0.627133,...,0.303473,0.299299,0.279607,0.293736,0.285091,0.257162,0.271633,0.285065,0.297832,0.297603
564,1.000000,0.642347,0.627133,0.627133,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,0.117602,0.115987,0.127690,0.116094,0.112681,0.117421,0.147476,0.134558,0.125899,0.125803
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
413,0.117421,0.259991,0.257162,0.257162,0.117421,0.117421,0.117421,0.117421,0.117421,0.117421,...,0.809902,0.798909,0.919231,0.836249,0.811854,1.000000,0.976046,0.547205,0.512058,0.511681
417,0.147476,0.274889,0.271633,0.271633,0.147476,0.147476,0.147476,0.147476,0.147476,0.147476,...,0.790516,0.779789,0.897221,0.816236,0.792429,0.976046,1.000000,0.534110,0.499806,0.499439
421,0.134558,0.284120,0.285065,0.285065,0.134558,0.134558,0.134558,0.134558,0.134558,0.134558,...,0.585479,0.577498,0.595224,0.541360,0.525518,0.547205,0.534110,1.000000,0.935777,0.935089
422,0.125899,0.282589,0.297832,0.297832,0.125899,0.125899,0.125899,0.125899,0.125899,0.125899,...,0.582963,0.575010,0.556964,0.539020,0.523237,0.512058,0.499806,0.935777,1.000000,0.999264
423,0.125803,0.282374,0.297603,0.297603,0.125803,0.125803,0.125803,0.125803,0.125803,0.125803,...,0.582526,0.576150,0.556548,0.538612,0.524270,0.511681,0.499439,0.935089,0.999264,1.000000

### Check the cluster statistics

The independet trials should each be evaluated according to the Deflated Sharpe Ratio(DSR).

In [8]:
from sbumt import (weights_min_var, expected_max_sr, 
                   probabilistic_sharpe_ratio, deflated_sharpe_ratio, cluster_statistics)

In [9]:
# Get the clusters
clusters_dict = model.get_optimal_clusters()
print(clusters_dict)

sil_s = model.get_silh_scores()

# Create Table
table_statistics = cluster_statistics(clusters_dict, data)
table_statistics

{0: ['560', '561', '562', '563', '564', '568', '572', '576', '580', '584', '588', '592', '596', '600', '604', '608', '612', '616', '620', '624', '628', '632', '636', '640', '641', '642', '643', '644', '648', '652', '656', '660', '664', '668', '672', '676', '680', '684', '688', '692', '696', '700', '704', '708', '712', '716', '800', '801', '802', '803', '804', '808', '812', '816', '820', '824', '828', '832', '836', '840', '844', '848', '852', '856', '860', '864', '868', '872', '876', '880', '881', '882', '883', '884', '888', '892', '896', '900', '904', '908', '912', '916', '920', '924', '928', '932', '936', '940', '944', '948', '952', '956', '960', '961', '962', '963', '964', '968', '972', '976', '980', '984', '988', '992', '996', '1000', '1004', '1008', '1012', '1016', '1020', '1024', '1028', '1032', '1036'], 1: ['160', '161', '162', '163', '164', '168', '172', '176', '180', '184', '188', '192', '196', '200', '204', '208', '212', '216', '220', '224', '228', '232', '236', '240', '241', '242', '243', '244', '248', '252', '256', '260', '264', '268', '272', '276', '280', '284', '288', '292', '296', '300', '304', '308', '312', '316', '320', '321', '322', '323', '324', '328', '332', '336', '340', '341', '342', '343', '344', '348', '352', '356', '360', '364', '368', '372', '376', '380', '384', '388', '392', '396', '480', '481', '482', '483', '484', '488', '492', '496', '500', '504', '508', '512', '516', '520', '524', '528', '532', '536', '540', '544', '548', '552', '556', '720', '721', '722', '723', '724', '728', '732', '736', '740', '744', '748', '752', '756', '760', '764', '768', '772', '776', '780', '784', '788', '792', '796'], 2: ['270', '271', '274', '275', '278', '279', '281', '282', '283', '285', '286', '287', '289', '290', '291', '293', '294', '295', '297', '298', '299', '301', '302', '303', '305', '306', '307', '309', '310', '311', '313', '314', '315', '317', '318', '319', '326', '327', '329', '330', '331', '333', '334', '335', '337', '338', '339', '345', '346', '347', '349', '350', '351', '353', '354', '355', '357', '358', '359', '361', '362', '363', '365', '366', '367', '369', '370', '371', '373', '374', '375', '377', '378', '379', '381', '382', '383', '385', '386', '387', '389', '390', '391', '393', '394', '395', '397', '398', '399', '554', '558', '565', '566', '567', '569', '570', '571', '573', '574', '575', '577', '578', '579', '581', '582', '583', '585', '586', '587', '589', '590', '591', '593', '594', '595', '597', '598', '599', '601', '602', '603', '605', '606', '607', '609', '610', '611', '613', '614', '615', '617', '618', '619', '621', '622', '623', '625', '626', '627', '629', '630', '631', '633', '634', '635', '637', '638', '639', '645', '646', '647', '649', '650', '651', '653', '654', '655', '657', '658', '659', '661', '662', '663', '665', '666', '667', '669', '670', '671', '673', '674', '675', '677', '678', '679', '681', '682', '683', '685', '686', '687', '689', '690', '691', '693', '694', '695', '697', '698', '699', '701', '702', '703', '705', '706', '707', '709', '710', '711', '713', '714', '715', '717', '718', '719', '805', '806', '807', '809', '810', '811', '813', '814', '815', '817', '818', '819', '821', '822', '823', '825', '826', '827', '829', '830', '831', '833', '834', '835', '837', '838', '839', '841', '842', '843', '845', '846', '847', '849', '850', '851', '853', '854', '855', '857', '858', '859', '861', '862', '863', '865', '866', '867', '869', '870', '871', '873', '874', '875', '877', '878', '879', '885', '886', '887', '889', '890', '891', '893', '894', '895', '897', '898', '899', '901', '902', '903', '905', '906', '907', '909', '910', '911', '913', '914', '915', '917', '918', '919', '921', '922', '923', '925', '926', '927', '929', '930', '931', '933', '934', '935', '937', '938', '939', '941', '942', '943', '945', '946', '947', '949', '950', '951', '953', '954', '955', '957', '958', '959', '965', '966', '967', '969', '970', '971', '973', '974', '975', '977', '978', '979', '981', '982', '983', '985', '986', '987', '989', '990', '991', '993', '994', '995', '997', '998', '999', '1001', '1002', '1003', '1005', '1006', '1007', '1009', '1010', '1011', '1013', '1014', '1015', '1017', '1018', '1019', '1021', '1022', '1023', '1025', '1026', '1027', '1029', '1030', '1031', '1033', '1034', '1035', '1037', '1038', '1039', '26', '27', '29', '30', '31', '33', '34', '35', '37', '38', '39', '41', '42', '43', '45', '46', '47', '49', '50', '51', '53', '54', '55', '57', '58', '59', '61', '62', '63', '65', '66', '67', '69', '70', '71', '73', '74', '75', '77', '78', '79', '90', '91', '94', '95', '98', '99', '105', '106', '107', '109', '110', '111', '113', '114', '115', '117', '118', '119', '121', '122', '123', '125', '126', '127', '129', '130', '131', '133', '134', '135', '137', '138', '139', '141', '142', '143', '145', '146', '147', '149', '150', '151', '153', '154', '155', '157', '158', '159', '165', '166', '167', '169', '170', '171', '173', '174', '175', '177', '178', '179', '181', '182', '183', '185', '186', '187', '189', '190', '191', '193', '194', '195', '197', '198', '199', '201', '202', '203', '205', '206', '207', '209', '210', '211', '213', '214', '215', '217', '218', '219', '221', '222', '223', '225', '226', '227', '229', '230', '231', '233', '234', '235', '237', '238', '239', '245', '246', '247', '249', '250', '251', '253', '254', '255', '257', '258', '259', '261', '262', '263', '265', '266', '267', '269', '273', '277', '325', '414', '415', '418', '419', '425', '426', '427', '429', '430', '431', '433', '434', '435', '437', '438', '439', '441', '442', '443', '445', '446', '447', '449', '450', '451', '453', '454', '455', '457', '458', '459', '461', '462', '463', '465', '466', '467', '469', '470', '471', '473', '474', '475', '477', '478', '479', '485', '486', '487', '489', '490', '491', '493', '494', '495', '497', '498', '499', '501', '502', '503', '505', '506', '507', '509', '510', '511', '513', '514', '515', '517', '518', '519', '521', '522', '523', '525', '526', '527', '529', '530', '531', '533', '534', '535', '537', '538', '539', '541', '542', '543', '545', '546', '547', '549', '550', '551', '553', '555', '557', '559', '725', '726', '727', '729', '730', '731', '733', '734', '735', '737', '738', '739', '741', '742', '743', '745', '746', '747', '749', '750', '751', '753', '754', '755', '757', '758', '759', '761', '762', '763', '765', '766', '767', '769', '770', '771', '773', '774', '775', '777', '778', '779', '781', '782', '783', '785', '786', '787', '789', '790', '791', '793', '794', '795', '797', '798', '799'], 3: ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '12', '13', '16', '17', '20', '21', '24', '28', '32', '36', '40', '44', '48', '52', '56', '60', '64', '68', '72', '76', '80', '81', '82', '83', '84', '85', '88', '92', '96', '100', '101', '104', '108', '112', '116', '120', '124', '128', '132', '136', '140', '144', '148', '152', '156', '400', '401', '402', '403', '404', '405', '408', '412', '416', '420', '424', '428', '432', '436', '440', '444', '448', '452', '456', '460', '464', '468', '472', '476', '10', '11', '14', '15', '18', '19', '22', '23', '25', '86', '87', '89', '93', '97', '102', '103', '406', '407', '409', '410', '411', '413', '417', '421', '422', '423']}

,Strat Count,aSR,SR,Skew,Kurt,T,sqrt(V[SR_k]),E[max SR_k],DFS
0,115.0,0.548064,0.034525,1.259200,70.389292,2412.0,0.019148,0.020146,0.762449
1,118.0,0.503583,0.031723,-3.233266,79.342056,2412.0,0.019148,0.020146,0.704218
2,702.0,0.883966,0.055685,-0.366252,7.770289,2412.0,0.019148,0.020146,0.957560
3,105.0,0.140971,0.008880,-3.493794,58.262329,2412.0,0.019148,0.020146,0.293052

## Run ONC without the max_scan parameter

Here we should see 5 independent trials found but athe runtime is much larger.

In [11]:
from onc import ONC_no_max_scan

In [ ]:
import os
os.environ["OMP_NUM_THREADS"] = '16'
# Supress all warnings due to running Kmeans on windows using all cores
import warnings
warnings.filterwarnings("ignore")
import time

# Fit ONC
start_time = time.time()
model4 = ONC_no_max_scan(data.corr(), repeat=450)
print('Fitting')
model4.fit()
end_time = time.time()
print("Time taken: ", end_time - start_time)

# Load from saved
# model2 = ONC(data.corr(), repeat=1)
# model2.load_results(pre_fix='official3')

#